### ISSUE TITLE
Support for 1024 height and width

### ISSUE THREAD

**Issue by Kkringg** [chenxwh/cog-sd-txt2imghd#2]
Any chance of getting 1024 as an available value for ori_width and ori_height?

I realize a 1024 x 1024 image will probably not work, but having sizes like 768 x 1024 and 1024 x 512 would be a great option.

Thanks in advance for the consideration! Big fan of this model.

**Comment by chenxwh** [comment]
Sure! I just added to the options in the new version on replicate.
